stages:
  - build

default:
  image: hectorlachambre/oc-expert-devops-docker-python
  services:
    - docker:26.1.4-dind
  before_script:
    - cat requirements.txt
    - pip install --no-cache-dir -r requirements.txt
    - pip list

build_application:
  stage: build
  script:
    - python3 docker-ci.py build
    - python3 docker-ci.py publish
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
    CI_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE
    CI_COMMIT_REF_SLUG: $CI_COMMIT_REF_SLUG
    CI_REGISTRY_USER: $CI_REGISTRY_USER
    CI_REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD