apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db-service
spec:
  selector:
    app: {{ .Release.Name }}-db
  ports:
    - protocol: TCP
      port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
  clusterIP: None